=== MR-M1CR0/New-folder/Task01/Family/family.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Family (Grandfather)>
<!ELEMENT Grandfather (#PCDATA|Father|Uncle|Aunt)*>
<!ELEMENT Father (#PCDATA|Mother|Daughter|Son)*>
<!ELEMENT Mother (#PCDATA)>
<!ELEMENT Daughter (#PCDATA)>
<!ELEMENT Son (#PCDATA)>
<!ELEMENT Uncle (#PCDATA)>
<!ELEMENT Aunt (#PCDATA)>
<!ATTLIST Father job (Engineer|Accountant|Doctor) #IMPLIED>
<!ATTLIST Daughter job (Engineer|Accountant|Doctor) #IMPLIED>
<!ATTLIST Daughter age CDATA #REQUIRED>
<!ATTLIST Son age CDATA #REQUIRED>
<!ATTLIST Son sport (tennis|football) "football">
<!ATTLIST Aunt sons CDATA "2">

=== MR-M1CR0/New-folder/Task01/Family/family.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Family SYSTEM "D:\XML-ITI\Day1\Lab1\Family\family.dtd">
<Family>
	<Grandfather>
		Mohamed
		<Father job="Engineer">
			Ahmed
			<Mother>Mona</Mother>
			<Daughter age="24" job="Engineer">Aya</Daughter>
			<Son age="20" sport="football">Ebrahim</Son>
		</Father>
		<Uncle>Khalid</Uncle>
		<Uncle>Saad</Uncle>
		<Aunt sons="2">Ghada</Aunt>
	</Grandfather>
</Family>
